# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PairMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PairMe

  target 'PairMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PairMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PairMe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PairMe-tvOS

  target 'PairMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
